### PR TITLE
Signature classification

### PR DESCRIPTION
**Pull request by zac-ng**
Pull request for generating signatures based on presence or absence of data.

Generating unique identifiers has been moved for to another notebook.

### CODE REVIEW

**Comment by petebryan** [comment]
@zac-ng looking good, i've added some code comments but most of them are minor things/best practice that you don't need to worry about right now but are worth thinking about, especially when moving code into MSTICPy.

I think a good thing to think about next is how someone is going to use this output - you've found good stuff but it doesn't feel the most usable in its current form. Maybe think about if you could create a function that helps take that json and create a user consumable output.

**Comment by zac-ng** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/microsoft/mstic-dataexpl/pull/4/discussion/) on ReviewNB
> 
> _petebryan commented on 2021-07-13T01:14:38Z_
> ----------------------------------------------------------------
> 
> Line #3.    with open('tables.txt') as file:
> Not a big deal in a notebook but when thinking about porting to MSTICPy generally good to try and catch common issues such as file not existing and provide an detailed message (MSTICPy has some custom exceptions for this) or to provide a default value in case the file isn't present (maybe in this case could be a short set of tables). Again at this stage it doesn't matter but something to bear in mind.

Is it preferable not to let python automatically raise a FileNotFound exception?

**Comment by petebryan** [comment]
> > View / edit / reply to [this conversation](https://app.reviewnb.com/microsoft/mstic-dataexpl/pull/4/discussion/) on ReviewNB
> > ## _petebryan commented on 2021-07-13T01:14:38Z_
> > Line #3.    with open('tables.txt') as file:
> > Not a big deal in a notebook but when thinking about porting to MSTICPy generally good to try and catch common issues such as file not existing and provide an detailed message (MSTICPy has some custom exceptions for this) or to provide a default value in case the file isn't present (maybe in this case could be a short set of tables). Again at this stage it doesn't matter but something to bear in mind.
> 
> Is it preferable not to let python automatically raise a FileNotFound exception?

This was our thinking early in the MSTICPy/Notebooks program but we quickly found that as many of the end users of these solutions aren't Python experts (mostly security analysts with some knowledge) they tend to see exceptions slightly differently, and typically if they just get a Python exception they see it as something that is broken and leave the whole thing. We developed a whole 'friendly' exception class to present in quite clear language what the errors were and how to fix them, and worked to catch as many exceptions as possible. 
If our audience was Python devs than absolutely leaving in the base exception would be fine, however we have to be a bit mindful of our audience with this work.

**Comment by zac-ng** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/microsoft/mstic-dataexpl/pull/4/discussion/) on ReviewNB
> 
> _petebryan commented on 2021-07-13T01:14:40Z_
> ----------------------------------------------------------------
> 
> Line #18.                    queryResult = qry_prov.exec_query(queryString)
> You could consider something here to check we get results and if not make a note of the face that the user might want to consider a different time frame

The user can specify a sample size or a time frame in weeks. Is there something else you wanted me to add? Or are you talking about adding support for custom query commands?

**Comment by zac-ng** [comment]
> Wondered if you'd tried "table | sample {sample_size}".
> 
> It's not a sample with any kind of guaranteed fairness of distribution. It might give you more consistent data set sizes though. E.g. if you queried some customer tables for 1+ weeks of data you might end up with Gb of data and query timeouts.
> 
> You could append "| limit 10000" or something to prevent data explosion.
> 
> Not sure though, if when using "sample" you might miss some rarer event types compared with just a flat query. Would be interesting to compare results from both types of query.
> 
> [View entire conversation](https://app.reviewnb.com/microsoft/mstic-dataexpl/pull/4/discussion/) on ReviewNB

The function generateData takes in an argument that allows the user to pass in the number of weeks, or the number of rows.  

I think rarer, older event types that may not longer occur may be more common when sampling.  A flat query I believe would be more representative of the data provided it's on a shorter timeframe I would think though.  That is an interesting thing to consider and I'll keep that in mind in the future.

**Comment by ianhelle** [comment]
Nice work @zac-ng !

**Pull request merged**
